<a href="https://colab.research.google.com/github/kevinnanda99/PYTORCH-WORKFLOW/blob/main/Pytorch_fundamentals_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

 INTRODUCTION TENSORS

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#vector
# dimension - num of square brackets
#shape - num of elements

vector = torch.tensor([7,7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix = torch.tensor([[1,2],[2,7]])
matrix
matrix[1]

tensor([2, 7])

In [ ]:
#tensor
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor2 = torch.tensor([[[1,2,3,4],[4,5,6,1],[7,8,9,4],[7,8,9,4]]])
tensor2
tensor2.shape

torch.Size([1, 4, 4])

RANDOM TENSOR

In [ ]:
random_tensor = torch.rand(7,5)
random_tensor
random_tensor.shape

torch.Size([7, 5])

# ZERO'S AND ONES

In [ ]:
zeros = torch.zeros(3,5)
zeros
ones = torch.ones(3,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

RANGE OF TENSORS

In [ ]:
rep = torch.arange(1,100,2)
rep

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
ten_zero = torch.zeros_like(rep)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

TENSOR DATA TYPES

In [ ]:
float_32 = torch.tensor([1,2,3,45,67], dtype=torch.float16, device=None,requires_grad=False)
float_32.dtype

torch.float16

In [ ]:
float_16_tensor = float_32.type(torch.float64)
float_16_tensor

tensor([ 1.,  2.,  3., 45., 67.], dtype=torch.float64)

MATRIX MULTIPLICATION

In [ ]:
torch.matmul(tensor,tensor)


tensor([[[ 30,  36,  42],
         [ 66,  81,  96],
         [102, 126, 150]]])

In [ ]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

In [ ]:
result = torch.matmul(tensor_a, tensor_b)
print(result)

tensor([[19, 22],
        [43, 50]])


In [ ]:
tensor_b

tensor([[5, 6],
        [7, 8]])

In [ ]:
tensor_b.T

tensor([[5, 7],
        [6, 8]])

In [ ]:
result1 = torch.matmul(tensor_a, tensor_b.T)
print(result1)

tensor([[17, 23],
        [39, 53]])


TENSOR AGGREGATION

In [ ]:
x = torch.arange(1,100,2)
x

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
torch.min(x), torch.max(x)

(tensor(1), tensor(99))

In [ ]:
torch.mean(x.type(torch.float32))

tensor(50.)

POSITIONAL MIN AND MAX

In [ ]:
x

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
x.argmin(), x.argmax()

(tensor(0), tensor(49))

In [ ]:
x[49], x[0]

(tensor(99), tensor(1))

RESHAPING, SQUEEZING, UNSQUEEZING TENSORS

In [ ]:
x.shape

torch.Size([50])

In [ ]:
x_reshape = x.reshape(1,50)
x_reshape

tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
         37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
         73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [ ]:
x_reshape

tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
         37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
         73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [ ]:
z = x.view(1,50)
z, z.shape

(tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
          37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
          73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]]),
 torch.Size([1, 50]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
          35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
          69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]],

        [[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
          35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
          69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]],

        [[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
          35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
          69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]],

        [[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
          35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
          69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]]])

In [ ]:
x_reshape

tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
         37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
         73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [ ]:
x_reshape.shape

torch.Size([1, 50])

In [ ]:
x_reshape.squeeze()

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
 x_reshape.shape

torch.Size([1, 50])

In [ ]:
y = torch.arange(1,50)
y
y.shape

torch.Size([49])

In [ ]:
y_reshape = y.reshape(1,49)
y_reshape


tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
         37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
y_squeezed = y_reshape.squeeze()
y_squeezed

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
y_squeezed.shape

torch.Size([49])

In [ ]:
y_unsqueezed = y_squeezed.unsqueeze(dim=1)
y_unsqueezed


tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30],
        [31],
        [32],
        [33],
        [34],
        [35],
        [36],
        [37],
        [38],
        [39],
        [40],
        [41],
        [42],
        [43],
        [44],
        [45],
        [46],
        [47],
        [48],
        [49]])

In [ ]:
y_unsqueezed.shape

torch.Size([49, 1])

In [ ]:
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
y_unsqueezed

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
         37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
y_unsqueezed.shape

torch.Size([1, 49])

PERMUTE

In [ ]:
x_new = torch.rand(size=(224,224,3))
x_new


tensor([[[0.8244, 0.2520, 0.0567],
         [0.3204, 0.0911, 0.6715],
         [0.9667, 0.2821, 0.1924],
         ...,
         [0.5250, 0.0297, 0.3124],
         [0.7545, 0.6762, 0.6233],
         [0.9625, 0.5769, 0.0131]],

        [[0.6862, 0.8754, 0.7005],
         [0.6265, 0.5995, 0.3450],
         [0.7878, 0.0061, 0.6205],
         ...,
         [0.2651, 0.8406, 0.4045],
         [0.7360, 0.6546, 0.1916],
         [0.1908, 0.4127, 0.3634]],

        [[0.3844, 0.7410, 0.2178],
         [0.7669, 0.5268, 0.4050],
         [0.8724, 0.2458, 0.2404],
         ...,
         [0.3705, 0.1287, 0.1394],
         [0.7229, 0.1427, 0.7863],
         [0.4753, 0.0087, 0.8275]],

        ...,

        [[0.5755, 0.2693, 0.9678],
         [0.8972, 0.6107, 0.6807],
         [0.3531, 0.9639, 0.5203],
         ...,
         [0.1810, 0.6988, 0.8473],
         [0.9656, 0.4317, 0.0246],
         [0.3304, 0.4808, 0.3274]],

        [[0.3985, 0.8603, 0.4629],
         [0.3387, 0.6610, 0.6018],
         [0.

In [ ]:
x_perm = x_new.permute(2,0,1)
x_perm

tensor([[[0.8244, 0.3204, 0.9667,  ..., 0.5250, 0.7545, 0.9625],
         [0.6862, 0.6265, 0.7878,  ..., 0.2651, 0.7360, 0.1908],
         [0.3844, 0.7669, 0.8724,  ..., 0.3705, 0.7229, 0.4753],
         ...,
         [0.5755, 0.8972, 0.3531,  ..., 0.1810, 0.9656, 0.3304],
         [0.3985, 0.3387, 0.6412,  ..., 0.8003, 0.4465, 0.0135],
         [0.1153, 0.4612, 0.6256,  ..., 0.1611, 0.7683, 0.9602]],

        [[0.2520, 0.0911, 0.2821,  ..., 0.0297, 0.6762, 0.5769],
         [0.8754, 0.5995, 0.0061,  ..., 0.8406, 0.6546, 0.4127],
         [0.7410, 0.5268, 0.2458,  ..., 0.1287, 0.1427, 0.0087],
         ...,
         [0.2693, 0.6107, 0.9639,  ..., 0.6988, 0.4317, 0.4808],
         [0.8603, 0.6610, 0.2799,  ..., 0.8973, 0.0649, 0.6215],
         [0.7081, 0.3842, 0.7478,  ..., 0.8899, 0.3160, 0.2452]],

        [[0.0567, 0.6715, 0.1924,  ..., 0.3124, 0.6233, 0.0131],
         [0.7005, 0.3450, 0.6205,  ..., 0.4045, 0.1916, 0.3634],
         [0.2178, 0.4050, 0.2404,  ..., 0.1394, 0.7863, 0.

In [ ]:
a = torch.randn(2, 3, 5)
a
a.size()

torch.Size([2, 3, 5])

In [ ]:
new_a = torch.permute(a, (1, 0, 2)).size()
new_a

torch.Size([3, 2, 5])

In [ ]:
new_a

torch.Size([3, 2, 5])

INDEXING SELECTING DATA FROM TENSORS

In [ ]:
b = torch.arange(1,10).reshape(1,3,3)
b, b.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
b[0][0][2], b[0][1][0], b[0][2][2], b[:,:,1], b[:,1,1], b[0][2][1]

(tensor(3), tensor(4), tensor(9), tensor([[2, 5, 8]]), tensor([5]), tensor(8))

In [ ]:
torch.cuda.is_available()


False

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'